// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PatientCare.Infrastructure.ReadDb;

#nullable disable

namespace PatientCare.Infrastructure.ReadDb.Migrations
{
    [DbContext(typeof(PatientCareReadDbContext))]
    [Migration("20260701091319_InitialPatientCareRead")]
    partial class InitialPatientCareRead
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PatientCare.Domain.Read.AppointmentReadItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AppointmentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PatientId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PhysicianId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ScheduledAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("AppointmentId");

                    b.HasIndex("PatientId");

                    b.ToTable("AppointmentReadItems", (string)null);
                });

            modelBuilder.Entity("PatientCare.Domain.Read.MedicalHistoryReadItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("PatientId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PhysicianId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("PatientId");

                    b.HasIndex("Timestamp");

                    b.ToTable("MedicalHistoryReadItems", (string)null);
                });

            modelBuilder.Entity("PatientCare.Domain.Read.PatientDossierReadModel", b =>
                {
                    b.Property<Guid>("PatientId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("LastUpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("PatientName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("PatientId");

                    b.ToTable("PatientDossiers", (string)null);
                });

            modelBuilder.Entity("PatientCare.Domain.Read.PrescriptionReadItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("MedicationDetails")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("PatientId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("PharmacyNotified")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("PatientId");

                    b.ToTable("PrescriptionReadItems", (string)null);
                });

            modelBuilder.Entity("PatientCare.Domain.Read.AppointmentReadItem", b =>
                {
                    b.HasOne("PatientCare.Domain.Read.PatientDossierReadModel", null)
                        .WithMany("UpcomingAppointments")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PatientCare.Domain.Read.MedicalHistoryReadItem", b =>
                {
                    b.HasOne("PatientCare.Domain.Read.PatientDossierReadModel", null)
                        .WithMany("MedicalHistory")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PatientCare.Domain.Read.PrescriptionReadItem", b =>
                {
                    b.HasOne("PatientCare.Domain.Read.PatientDossierReadModel", null)
                        .WithMany("ActivePrescriptions")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PatientCare.Domain.Read.PatientDossierReadModel", b =>
                {
                    b.Navigation("ActivePrescriptions");

                    b.Navigation("MedicalHistory");

                    b.Navigation("UpcomingAppointments");
                });
#pragma warning restore 612, 618
        }
    }
}
